### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by KaushikDuddala** [deltacv/EOCV-Sim#104]
When I attempt to start the program from terminal it seems to work for a second and shows its logo but then crashes shortly after.

1. Run "java -jar /Volumes/FTC/EOCV-Sim-3.5.1-all.jar"
2. Wait
3. See error

**Expected behavior**
Program launches

**Screenshots**
![Screenshot 2023-09-25 at 11 38 20 AM](https://github.com/deltacv/EOCV-Sim/assets/72582623/5fcdc61a-a6c3-4546-85e6-6a25a1e55407)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Processor architecture: x86
 - EOCV-Sim Version 3.5.1
 - Java version: 10.0.2
 - logs: [crashreport-eocvsim-2023_09_25-11.37.43.log](https://github.com/deltacv/EOCV-Sim/files/12717639/crashreport-eocvsim-2023_09_25-11.37.43.log)

**Comment by serivesmejia** [comment]
Hi ! Thank you for reporting this issue. It's a rather strange bug but I should have a fix uploaded in a few moments. I'll get back to you.

**Comment by serivesmejia** [comment]
I have pushed a development release that should fix this issue; https://github.com/deltacv/EOCV-Sim/releases/tag/Dev

If you could try it out and let me know how it works that would be of great help to be able to close this issue. Thanks!

**Comment by KaushikDuddala** [comment]
Launches perfectly! Thanks!
