### ISSUE TITLE
OpenCV Pipeline Crash

### ISSUE THREAD

**Issue by weerobots** [deltacv/EOCV-Sim#105]
Running either of the attached pipelines with the attached images results in the following error fairly quickly.

Log reports attached.

[SpikeTapePipelineBlue.zip](https://github.com/deltacv/EOCV-Sim/files/12732550/SpikeTapePipelineBlue.zip)
![BlueFTC-R](https://github.com/deltacv/EOCV-Sim/assets/143899357/bbe0de3d-4460-4327-a987-1c47d6a90006)
![RedFTC](https://github.com/deltacv/EOCV-Sim/assets/143899357/aa960a4a-7d10-4182-b481-48aab26cc869)

]

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - Processor architecture:  x86_64,
 - Java 11
[crashreport-eocvsim-2023_09_25-11.07.00.zip](https://github.com/deltacv/EOCV-Sim/files/12732604/crashreport-eocvsim-2023_09_25-11.07.00.zip)

 - EOCV-Sim Version "EOCV-Sim-3.5.2-all.jar"

**Comment by serivesmejia** [comment]
Hi! Thank you for reporting this issue. It seems to be related to #104 so we'll keep track in that thread. I'll let you know once I have a working fix you can test.

**Comment by serivesmejia** [comment]
I have pushed a development release that should fix this issue; https://github.com/deltacv/EOCV-Sim/releases/tag/Dev

If you could try it out and let me know how it works that would be of great help to be able to close this issue. Thanks!

**Comment by weerobots** [comment]
The problem may be some bad opencv in the pipeline. I am able to run the attached pipeline with no problems.
[Working Pipelins.txt](https://github.com/deltacv/EOCV-Sim/files/12754578/Working.Pipelins.txt)
I'm closing the bug report

**Comment by weerobots** [comment]
See previous comment
