### ISSUE TITLE
Perhaps a problem...

### ISSUE THREAD

**Issue by alan412** [deltacv/EOCV-Sim#110]
I had this reported with the LearnJavaForFTC: https://github.com/alan412/LearnJavaForFTC/issues/65

Is it possible this is a problem in EOCV-Sim?

Thanks,

Alan

**Comment by serivesmejia** [comment]
It does seem like an overlook of mine, internally I reuse the same instance of native Paint when an android Paint is passed to the constructor, I will check if I can instead make a new cloned instance instead.

**Comment by serivesmejia** [comment]
Fixed in [EOCV-Sim v3.4.3](https://github.com/deltacv/EOCV-Sim/releases/tag/v3.5.3)
