### ISSUE TITLE
Accidentally set workspace location to C drive and the simulator doesn't open

### ISSUE THREAD

**Issue by PaigeTurtle** [deltacv/EOCV-Sim#125]
**Describe the bug**
While choosing workspace, I accidentally set workspace as C drive and the simulator instantly closed. I tried uninstalling it and reinstalling different versions but problem persists.

**To Reproduce**
1. choose "select workspace"
2. set it as C drive (C:\)

**Expected behavior**
Instantly closes program and does not open in any way

device: Windows 11

[crashreport-eocvsim-2024_11_14-18.16.58.log](https://github.com/user-attachments/files/17760605/crashreport-eocvsim-2024_11_14-18.16.58.log)

**Comment by serivesmejia** [comment]
I'll make sure to handle that error in the future so that the sim does not crash. For now, delete the folder in C:/Users/<your user>/.eocvsim
This will wipe all user preferences.
