### ISSUE TITLE
Cannot add image source

### ISSUE THREAD

**Issue by PaigeTurtle** [deltacv/EOCV-Sim#130]
**Describe the bug**
Cannot add image source, always results in "unable to load selected file".

**To Reproduce**
1.Open EOCV sim
2. drag a png or jpeg image to the image source tab
or
2. select create
    a. select image
    b. select image from computer and select open

**Expected behavior**
The image does not add, and results in "unable to load selected file"

**Screenshots**
![Screenshot 2024-12-04 203703](https://github.com/user-attachments/assets/3996a2cb-92fa-4ec5-9053-e129a8975451)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - EOCV-Sim Version 3.8.3

**Additional context**
I have tried camera and video also, but those work fine.

**Comment by serivesmejia** [comment]
Hi ! Thank you for reporting the issue, do you think you can, first of all, reproduce the issue by trying to import an image, then going to Help -> Export logs and send the logs file?
Also, just to make sure, are you able to open the image using windows?

**Comment by PaigeTurtle** [comment]
HI! I can open every single image I tried using windows. Here is the log:
[crashreport-eocvsim-2024_12_05-10.25.08.log](https://github.com/user-attachments/files/18027966/crashreport-eocvsim-2024_12_05-10.25.08.log)

**Comment by serivesmejia** [comment]
Hmmm, I can't catch anything wrong in the logs. Let's check two things;
- Are you able to load the default image sources properly (e.g when you select Ultimate Goal 0 Ring, does it display properly?)
- Do you think you could attach the image you're trying to use so that i might try to reproduce the issue on my end?

**Comment by PaigeTurtle** [comment]
I can load all the default image sources properly. Here are some of the images:
![modified](https://github.com/user-attachments/assets/73b7c157-cdf3-4c44-ab61-131d9b18f347)
![Screenshot 2024-10-31 184103](https://github.com/user-attachments/assets/30aa2046-af22-47b9-bfbd-6b00855a8d87)

**Comment by PaigeTurtle** [comment]
I just dragged the images that I sent from github and pasted into the sources and it works fine. I think it was a problem with the images or the folders storing it somehow. Thank you
