### ISSUE TITLE
Java Application Launch Failed - Could not find or load main class

### ISSUE THREAD

**Issue by LightenDarkness** [deltacv/EOCV-Sim#67]
**Describe the bug**
Running the jar file will result in an "Java Application Launch Failed" system popup. Running from console will result in this error:
Error: Could not find or load main class EOCV-Sim-3.3.1-all.jar
Caused by: java.lang.ClassNotFoundException: EOCV-Sim-3.3.1-all.jar

**To Reproduce**
Run the program (On an M1 Mac?)

**Expected behavior**
The application to run

**Desktop:**
 - OS: MacOS Big Sur
 - Version 11.6
 - Mac M1

**Comment by LightenDarkness** [comment]
I see there is another closed issue on the same subject. My mistake.

**Comment by serivesmejia** [comment]
> I see there is another closed issue on the same subject. My mistake.

No worries! Though, your issue actually is a different thing. But I recommend downloading an x86 JVM as we discussed on the other issue and make sure you use the correct command, `java -jar "EOCV-Sim-3.3.1-all.jar"`, or run the jar file double clicking it in the file explorer

**Comment by serivesmejia** [comment]
I reopened in case you need further help :)

**Comment by LightenDarkness** [comment]
I appreciate it, thanks :). I finally got it working, I was using the wrong command in the terminal, and when double-clicking in finder it crashed due to the M1 issue.

I got it working now using SDKMAN (This makes it easy to switch back and forth from and to the 64x versions), installing 18.ea.22-open, and setting the terminal to rosetta.

**Comment by youssifsamir** [comment]
Could you please explain to me in steps what exactly to do as I'm facing the exact same issue. Thanks!
