### ISSUE TITLE
Keeps crashing right after opening

### ISSUE THREAD

**Issue by Abdullahquraishi429** [deltacv/EOCV-Sim#83]
**Describe the bug**
Idk if this is a bug or not but I'm on a mac and whenever I open it through finder, it opens for a sec but crashes. Then I tried opening it through the command prompt like the documentation says but it still opens for sometime but crashes. 
<img width="574" alt="Screen Shot 2022-07-31 at 1 22 59 AM" src="https://user-images.githubusercontent.com/88250392/182013076-d05b92fe-0f98-4e25-a9d9-3270759f7623.png">

**To Reproduce**
1. Download the EOCV Sim
2. Go to finder and hold control and click on the file, then click open
3. It'll open for a sec but immediately close for me
4. If that doesn't work try using the terminal
5. cd downloads
6. java -jar "EOCV-Sim-3.4.1-all.jar"   Then click Enter
7. For me it opens for a short time but then crashes

**Expected behavior**
I expected it to just open and stay open not abruptly crash
**Screenshots**
<img width="574" alt="Screen Shot 2022-07-31 at 1 22 59 AM" src="https://user-images.githubusercontent.com/88250392/182013301-ccc1238a-8608-4c61-a695-9518dd4400c7.png">

**Desktop (please complete the following information):**
 - OS: [Mac OS Monterey]
 - Processor architecture: [M1]
 - EOCV-Sim Version [3.4.1]
 - Attach logs if possible [e.g autogenerated crash report files in the same directory as the jar file or the console output]

**Additional context**
idk if this is just a problem with mac or a problem with the M1 chip that I have

**Comment by serivesmejia** [comment]
Hi, sorry this is happening to you. Could you navigate through the folders /Users/<your user name>/.eocvsim/default_workspace and delete the apriltag detection pipeline.java file in there?

You might need to turn on the display of hidden folders to see .eocvsim

**Comment by serivesmejia** [comment]
Fixed on v3.4.2 as AprilTags are not supported
