### ISSUE TITLE
Package doesn't exist when it is in gradle

### ISSUE THREAD

**Issue by js802025** [deltacv/EOCV-Sim#84]
EOCV-Sim says packages don't exist when ./gradlew build runs fine.

To Reproduce:
1. Add dependency in gradle
2. Import package in pipeline
3. get error

**Expected behavior**
To find dependency and import.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11

**Comment by serivesmejia** [comment]
Hi! The current design of Gradle workspaces isn't really meant for actually adding your dependencies there sadly, as they're ignored when eocv sim buids your code with a different workflow, the only purpose of Gradle is to provide intellisense for opencv functions in vs code. This might be improved in the future. If you were looking to add libraries you can try adding their source code to the workspace.

**Comment by js802025** [comment]
Yeah, that's what I figured. Thanks for the help.

**Comment by serivesmejia** [comment]
Feel free to reopen this issue or make a new one if you need it. Thanks!
