### ISSUE TITLE
Can't open workspace on M1 Mac - NPE error when pasting pathname.

### ISSUE THREAD

**Issue by SriramKalki** [deltacv/EOCV-Sim#88]
I am trying to open my workspace on EOCV-Sim. However, when I try to browse for my workspace using Select Workspace, it shows nothing (only main folders). I tried copying my path to my vision folder and pressing Enter, however it gives me an NPE (curiously though it creates a json file).

**Screenshots**
![image](https://user-images.githubusercontent.com/79238833/211982017-da5a36ca-1ba6-45bb-9faa-3ba96816ff59.png)
![image2](https://user-images.githubusercontent.com/79238833/211982074-d4c6909d-398e-47a8-8e84-ad21f78f607e.png)

**Desktop (please complete the following information):**
2020 M1 Mac Mini on Monterey 12.4

**Comment by serivesmejia** [comment]
Hi, sorry for the delay (github fails to notify me yet again...)
Could you share your eocvsim_config.json file? In your case it would be under /Users/sriram/.eocvsim
Also your eocvsim_workspace.json file that was created under the path you tried to add. Thanks!

In the meantime, you might delete you eocvsim_config file and place your pipeline source files on the default workspace in /Users/sriram/.eocvsim/default_workspace to see if that works.

**Comment by SriramKalki** [comment]
The json under /sriram:
`
{
  "simTheme": "Light",
  "zoom": 1.0,
  "pipelineMaxFps": "MEDIUM",
  "pipelineTimeout": "MEDIUM",
  "pauseOnImages": true,
  "videoRecordingSize": {
    "width": 640.0,
    "height": 480.0
  },
  "videoRecordingFps": "MEDIUM",
  "preferredWebcamDriver": "OpenIMAJ",
  "workspacePath": "/Users/sriram",
  "globalTunableFieldsConfig": {
    "sliderRange": {
      "width": 0.0,
      "height": 255.0
    },
    "pickerColorSpace": "RGB",
    "fieldPanelMode": "TEXTBOXES",
    "source": "GLOBAL_DEFAULT"
  },
  "specificTunableFieldConfig": {}
}
`

The json under where I gave the path:
`
{
  "sourcesPath": ".",
  "resourcesPath": ".",
  "excludedPaths": [],
  "excludedFileExtensions": []
}
`

(Github doesn't let me attach json)
Thanks! I will try the solution you gave.

**Comment by SriramKalki** [comment]
This bug (not being able to upload files) also reproduces when you try to use images/video for sources. Where the the default images stored on the local computer?

-Sriram

**Comment by serivesmejia** [comment]
I'm starting to think it's some sort of Mac restriction stuff which isn't allowing the JVM to see the file system... Could you try the solution of this https://stackoverflow.com/questions/65469536/ to see if it works? I have very little Mac knowledge so I'm short on this area but that might hopefully work

As for the default images, they're stored in the jar file and extracted on runtime in the folder specified by `System.getProperty("java.io.tmpdir")`

**Comment by SriramKalki** [comment]
Great! It works now.

Small change to that stackoverflow solution for me: They said to add "Jar Launcher" in \System\Cores... , however it was named "Java Launcher".
![image](https://user-images.githubusercontent.com/79238833/213305965-fb1bc556-dd8f-471a-91ba-580ce151096d.png)
