### ISSUE TITLE
Can't open .jar file

### ISSUE THREAD

**Issue by Arav-R** [deltacv/EOCV-Sim#89]
**Describe the bug**
I just downloaded the .jar file on M1 mac and opening the file through finder does nothing. When opening through terminal it says "[main/ERROR]: [EOCVSim] The sim will exit now as it's impossible to continue execution without OpenCV". I tried downloading the latest Java and still the same thing is happening. Restarting computer didn't help either.

**To Reproduce**
1. Download the latest .jar file from 3.4.2
2. Using terminal open the file with:  java -jar "EOCV-Sim-3.4.2-all.jar"
3. See error in terminal

**Expected behavior**
I expected it to open the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/63694299/212780085-fd131312-3f7a-4d9b-9b36-289e71f00f9c.png)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0.1
 - Processor architecture: M1 Pro
 - EOCV-Sim Version 3.4.2
 - Attach logs if possible [e.g autogenerated crash report files in the same directory as the jar file or the console output] 
[Downloadscrashreport-eocvsim-2023_01_16-17.22.50.log](https://github.com/deltacv/EOCV-Sim/files/10429981/Downloadscrashreport-eocvsim-2023_01_16-17.22.50.log)

**Comment by serivesmejia** [comment]
Hi, can you try this release https://github.com/deltacv/EOCV-Sim/releases/tag/Dev ?

It provides support for M1, i haven't been able to release it officially due to lack of testing so it would be helpful if you could give me feedback afterwards to confirm it works. Thanks!
