### ISSUE TITLE
User-created/modified pipelines don't appear

### ISSUE THREAD

**Issue by L3eC** [deltacv/EOCV-Sim#90]
**Pipelines that I create or modify do not appear.** I tried three things, none of which led to a success: First, I created a new folder, pasted one of my team's pipelines in it, and opened that folder in the simulator. The pipeline did not appear in the list of pipelines. The second thing I tried was pasting my team's pipeline in the default folder at ~/.eocvsim/default_workspace. The pipeline didn't appear in the list after doing this either. The last thing I tried was modifying one of the pre-existing pipelines in the default workspace. The pipeline I modified disappeared from the list.

**To Reproduce**
1. Install EOCV-Sim.
2. Paste a pipeline into a new folder anywhere.
3. Open the folder.
4. See that your pipeline doesn't appear.

**Expected behavior**
The behaviour I expected was for my pipeline to show up.
**Screenshots**
![Screenshot (24)](https://user-images.githubusercontent.com/103331501/216500076-535d2e8b-93b3-4b34-8f8a-1b9cf5f8473e.png)
BasicPipeline is one of my team's pipelines, and I had modified StageSwitchingPipeline, which seems to have caused it to disappear.

**Desktop:**
 - OS: Windows 10
 - Processor architecture: x86
 - EOCV-Sim Version: 3.4.2
 - Attach logs if possible [crashreport-eocvsim-2023_02_02-18.31.04.log](https://github.com/deltacv/EOCV-Sim/files/10575127/crashreport-eocvsim-2023_02_02-18.31.04.log)

Thanks.

**Comment by serivesmejia** [comment]
Hi, sorry for the delay. I'm kinda clueless here but lets try a few things. Could you send me the source code of your pipeline?
